name: Build and Run Unit Tests on Render

on:
  push:
    branches: [ "render-deployment" ]

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET version 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Execute NUnit Tests
      run: dotnet test --no-build --verbosity normal
  
  deploy_to_render:
    needs: build_unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
